/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/relay-proxy/wrangler.jsonc --include-runtime=false workers/relay-proxy/src/worker-configuration.d.ts` (hash: 2dba9ef09e82393e8e32f553ce003aac)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
	ORIGIN_URL: "https://relay.example.com";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ORIGIN_URL">> {}
}
